from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, model_validator

from .enums import AgentType, AuditDepth, Severity


# ─── Sub-models ───────────────────────────────────────────────────────────────

class AgentConfig(BaseModel):
    """
    Tailored configuration for a single specialist agent within an AuditPlan.
    Generated by the Orchestrator based on SiteProfile — not static defaults.
    """

    enabled: bool = Field(
        True,
        description="Whether this agent should run. Orchestrator may disable agents that aren't relevant.",
    )
    depth: AuditDepth = Field(
        AuditDepth.STANDARD,
        description="Audit depth. Deep triggers more tool calls and sub-investigations.",
    )
    priority_areas: List[str] = Field(
        default_factory=list,
        description=(
            "Specific sub-categories this agent should focus on first. "
            "Derived from recon signals. E.g. SEO agent: ['structured_data', 'meta_tags']"
        ),
    )
    skip_areas: List[str] = Field(
        default_factory=list,
        description=(
            "Sub-categories this agent should skip. "
            "Used when recon determines they are not applicable (e.g. no ecommerce = skip product schema)."
        ),
    )
    context_from_agents: List[AgentType] = Field(
        default_factory=list,
        description=(
            "Other agents whose findings this agent should read before starting. "
            "Creates a soft dependency without blocking parallelism — the agent waits "
            "only if those findings are already available, otherwise proceeds without them."
        ),
    )
    special_instructions: Optional[str] = Field(
        None,
        description=(
            "Free-text instructions from the Orchestrator specific to this site. "
            "E.g. 'This is a Shopify store — prioritize product page structured data and checkout performance.'"
        ),
    )
    expected_finding_count: Optional[int] = Field(
        None,
        description="Orchestrator's estimate of how many findings this agent will produce (for UI progress)",
    )


class PlanRationale(BaseModel):
    """
    The Orchestrator's reasoning for the audit plan it generated.
    Persisted for observability and debugging.
    """
    site_summary: str = Field(
        ...,
        description="One-paragraph summary of what the Orchestrator understood about the site",
    )
    key_recon_signals: List[str] = Field(
        default_factory=list,
        description="The recon signals that most influenced the plan",
    )
    agents_prioritized: List[AgentType] = Field(
        default_factory=list,
        description="Agents the Orchestrator expects to produce the most impactful findings",
    )
    agents_deprioritized: List[AgentType] = Field(
        default_factory=list,
        description="Agents running at standard depth because recon didn't flag their domain",
    )
    agents_skipped: List[AgentType] = Field(
        default_factory=list,
        description="Agents not running and why",
    )
    skip_reasons: Dict[str, str] = Field(
        default_factory=dict,
        description="Map of agent_type → reason for skipping",
    )
    estimated_duration_seconds: int = Field(
        ...,
        description="Orchestrator's estimate of total audit duration",
    )


class CrossAgentDependency(BaseModel):
    """
    A declared dependency between two agents.
    Used by the Orchestrator to inject findings from one agent into another's context.
    """
    provider_agent: AgentType = Field(..., description="The agent producing the findings")
    consumer_agent: AgentType = Field(..., description="The agent that will read those findings")
    finding_categories: List[str] = Field(
        ...,
        description="Which finding categories the consumer needs from the provider",
    )
    rationale: str = Field(
        ...,
        description="Why this cross-agent context improves the consumer's analysis",
    )


# ─── Core Model ───────────────────────────────────────────────────────────────

class AuditPlan(BaseModel):
    """
    The Orchestrator's tailored execution plan for a specific audit.
    Generated dynamically from SiteProfile — this is not a static template.

    This model is what separates a scripted pipeline from a genuinely agentic system.
    The plan differs meaningfully between a SaaS product, a blog, and an ecommerce store.
    """

    id: UUID = Field(default_factory=uuid4)
    audit_id: UUID = Field(..., description="Parent audit session")
    site_profile_id: UUID = Field(..., description="The SiteProfile this plan was derived from")

    # ── Agent Configurations ────────────────────────────────────────────────
    agent_configs: Dict[AgentType, AgentConfig] = Field(
        ...,
        description=(
            "Per-agent configuration keyed by AgentType. "
            "Every AgentType must have an entry — even skipped agents (enabled=False)."
        ),
    )

    # ── Cross-Agent Data Flow ───────────────────────────────────────────────
    cross_agent_dependencies: List[CrossAgentDependency] = Field(
        default_factory=list,
        description=(
            "Declared data flow between agents. "
            "Orchestrator uses this to inject findings from provider into consumer's context "
            "when those findings become available."
        ),
    )

    # ── Execution Order ─────────────────────────────────────────────────────
    parallel_agents: List[AgentType] = Field(
        ...,
        description="Agents that run simultaneously after planning completes",
    )
    sequential_after: Dict[str, List[AgentType]] = Field(
        default_factory=dict,
        description=(
            "Agents that must wait for specific other agents to complete. "
            "Keyed by the blocking agent, value is list of agents it unblocks. "
            "Used only when a hard dependency exists (rare — prefer soft context injection)."
        ),
    )

    # ── Rationale ───────────────────────────────────────────────────────────
    rationale: PlanRationale

    # ── Meta ─────────────────────────────────────────────────────────────────
    created_at: datetime = Field(default_factory=datetime.utcnow)

    @model_validator(mode="after")
    def validate_all_agents_configured(self) -> "AuditPlan":
        specialist_agents = [a for a in AgentType if a != AgentType.ORCHESTRATOR]
        missing = [a for a in specialist_agents if a not in self.agent_configs]
        if missing:
            raise ValueError(f"AuditPlan is missing configuration for agents: {missing}")
        return self

    @model_validator(mode="after")
    def validate_parallel_agents_are_configured(self) -> "AuditPlan":
        for agent in self.parallel_agents:
            if agent not in self.agent_configs:
                raise ValueError(f"Parallel agent {agent} has no AgentConfig entry")
            if not self.agent_configs[agent].enabled:
                raise ValueError(f"Agent {agent} is in parallel_agents but is disabled")
        return self

    @property
    def enabled_agents(self) -> List[AgentType]:
        return [a for a, cfg in self.agent_configs.items() if cfg.enabled]

    @property
    def deep_agents(self) -> List[AgentType]:
        return [a for a, cfg in self.agent_configs.items() if cfg.depth == AuditDepth.DEEP]

    def get_config(self, agent: AgentType) -> AgentConfig:
        return self.agent_configs[agent]
