from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, computed_field, field_validator, model_validator

from .enums import (
    AgentType,
    FindingCategory,
    FindingRelationshipType,
    ImplementationEffort,
    Severity,
)


# ─── Sub-models ───────────────────────────────────────────────────────────────

class FindingEvidence(BaseModel):
    """
    The raw, structured data that produced a finding.
    Every finding must have evidence — no assertions without proof.
    """
    tool_name: str = Field(
        ...,
        description="The tool that produced this evidence (from the Tool Catalog)",
    )
    raw_data: Dict[str, Any] = Field(
        ...,
        description="The tool's structured output — the actual numbers, elements, or content",
    )
    affected_elements: List[str] = Field(
        default_factory=list,
        description=(
            "Human-readable identifiers of what is affected: "
            "CSS selectors, URLs, heading text, image src, etc."
        ),
    )
    affected_count: Optional[int] = Field(
        None,
        description="How many elements/instances are affected (for scale context)",
    )
    screenshot_path: Optional[str] = Field(
        None,
        description="Path to a screenshot that visually demonstrates the issue",
    )
    source_url: Optional[str] = Field(
        None,
        description="The specific URL where this evidence was collected (if not the root URL)",
    )
    metric_value: Optional[str] = Field(
        None,
        description=(
            "The key metric in human-readable form. "
            "E.g. '4.2s', '23 violations', '0.42 contrast ratio', '148 KB uncompressed'"
        ),
    )
    metric_threshold: Optional[str] = Field(
        None,
        description="The acceptable threshold for comparison. E.g. '2.5s', '4.5:1 contrast ratio'",
    )


class FixSuggestion(BaseModel):
    """
    Concrete, actionable fix recommendation attached to a finding.
    Generated by the specialist agent or claude_fix_generator tool.
    """
    description: str = Field(
        ...,
        description="Step-by-step explanation of how to fix this",
    )
    code_snippet: Optional[str] = Field(
        None,
        description="Code, markup, config, or copy that implements the fix",
    )
    snippet_language: Optional[str] = Field(
        None,
        description="Language hint for syntax highlighting (html, css, js, json, etc.)",
    )
    documentation_url: Optional[str] = Field(
        None,
        description="Official reference for the correct implementation",
    )
    verification_steps: List[str] = Field(
        default_factory=list,
        description="How to verify the fix was applied correctly",
    )


class FindingRelationship(BaseModel):
    """
    A typed link between this finding and another finding in the same audit.
    Populated by the Synthesis Agent during cross-referencing.
    """
    related_finding_id: UUID
    relationship_type: FindingRelationshipType
    description: str = Field(
        ...,
        description="Why these findings are related and what it means for prioritization",
    )


# ─── Core Model ───────────────────────────────────────────────────────────────

class Finding(BaseModel):
    """
    A single audited issue or observation produced by a specialist agent.

    Every finding is a structured contract — not a free-text note.
    The priority_score computed field drives the Synthesis Agent's roadmap ordering.
    """

    id: UUID = Field(default_factory=uuid4)
    audit_id: UUID = Field(..., description="Parent audit session")
    agent: AgentType = Field(..., description="The agent that produced this finding")
    category: FindingCategory = Field(
        ...,
        description="Subcategory within the agent's domain",
    )

    # ── Identity ─────────────────────────────────────────────────────────────
    title: str = Field(
        ...,
        min_length=5,
        max_length=120,
        description="Short, specific title. States the problem, not the symptom. E.g. 'LCP exceeds 4s threshold on homepage'",
    )
    description: str = Field(
        ...,
        min_length=20,
        description="Full description of the finding: what it is, where it is, and why it matters",
    )

    # ── Impact ───────────────────────────────────────────────────────────────
    severity: Severity = Field(
        ...,
        description="Categorical severity of the issue",
    )
    business_impact: str = Field(
        ...,
        description=(
            "Business-language description of what this costs the site. "
            "E.g. 'Slow LCP directly reduces organic ranking and increases bounce rate — "
            "a 1s delay reduces conversions by ~7%.'"
        ),
    )
    impact_score: int = Field(
        ...,
        ge=1,
        le=10,
        description=(
            "Numeric impact score 1–10. "
            "Factors in: severity, affected user percentage, business goal alignment. "
            "10 = directly and significantly harms the site's primary goal."
        ),
    )

    # ── Effort ───────────────────────────────────────────────────────────────
    effort: ImplementationEffort = Field(
        ...,
        description="Categorical implementation effort",
    )
    effort_hours_min: int = Field(..., ge=0, description="Minimum estimated fix hours")
    effort_hours_max: int = Field(..., ge=0, description="Maximum estimated fix hours")

    # ── Fix ──────────────────────────────────────────────────────────────────
    fix_suggestion: FixSuggestion = Field(
        ...,
        description="Concrete, actionable fix — not a generic recommendation",
    )

    # ── Confidence ───────────────────────────────────────────────────────────
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Agent's confidence that this is a real issue. "
            "Tool-derived findings (e.g. Lighthouse, axe) have high confidence (0.9+). "
            "AI-inferred findings (e.g. content quality) may have lower confidence (0.6–0.8)."
        ),
    )

    # ── Evidence ─────────────────────────────────────────────────────────────
    evidence: FindingEvidence = Field(
        ...,
        description="The tool output and affected elements that produced this finding",
    )

    # ── Relationships (populated by Synthesis Agent) ─────────────────────────
    relationships: List[FindingRelationship] = Field(
        default_factory=list,
        description="Links to related findings from other agents. Written by Synthesis Agent.",
    )

    # ── Metadata ─────────────────────────────────────────────────────────────
    tags: List[str] = Field(
        default_factory=list,
        description=(
            "Free-form tags for filtering and cross-referencing. "
            "E.g. ['above-fold', 'mobile', 'conversion', 'quick-win']"
        ),
    )
    wcag_criteria: Optional[str] = Field(
        None,
        description="WCAG criterion reference if applicable (e.g. '1.4.3 Contrast (Minimum)')",
    )
    is_synthesis_finding: bool = Field(
        False,
        description="True if this finding was created by the Synthesis Agent (compound/cross-domain issue)",
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # ── Computed ─────────────────────────────────────────────────────────────
    @computed_field
    @property
    def priority_score(self) -> float:
        """
        Composite priority score used by the Synthesis Agent to rank roadmap items.

        Formula: (impact_score × severity_weight × confidence) / effort_divisor

        Range: ~0.3 (low impact, hard, low confidence) to ~50 (critical, easy, certain).
        Higher = fix sooner.
        """
        return (
            self.impact_score
            * self.severity.weight
            * self.confidence
        ) / self.effort.divisor

    @computed_field
    @property
    def effort_hours_estimate(self) -> str:
        if self.effort_hours_min == self.effort_hours_max:
            return f"{self.effort_hours_min}h"
        return f"{self.effort_hours_min}–{self.effort_hours_max}h"

    # ── Validators ───────────────────────────────────────────────────────────
    @model_validator(mode="after")
    def validate_effort_hours_range(self) -> "Finding":
        if self.effort_hours_min > self.effort_hours_max:
            raise ValueError("effort_hours_min must be <= effort_hours_max")
        return self

    @model_validator(mode="after")
    def validate_effort_hours_align_with_category(self) -> "Finding":
        limits = {
            ImplementationEffort.EASY:   (0, 4),
            ImplementationEffort.MEDIUM: (1, 16),
            ImplementationEffort.HARD:   (8, 200),
        }
        lo, hi = limits[self.effort]
        if not (lo <= self.effort_hours_max <= hi):
            raise ValueError(
                f"effort_hours_max={self.effort_hours_max} is inconsistent with effort={self.effort}"
            )
        return self

    @model_validator(mode="after")
    def synthesis_findings_must_have_relationships(self) -> "Finding":
        if self.is_synthesis_finding and not self.relationships:
            raise ValueError("Synthesis findings must reference at least one related finding")
        return self

    class Config:
        json_schema_extra = {
            "example": {
                "title": "LCP exceeds 4.2s — well above 2.5s threshold",
                "severity": "critical",
                "impact_score": 9,
                "effort": "medium",
                "confidence": 0.97,
                "business_impact": "Google uses LCP as a Core Web Vital ranking signal. At 4.2s you are in the 'Poor' band, which suppresses organic rankings and increases bounce rate by an estimated 32%.",
            }
        }
